server:
    port: 11115
    
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pay
    username: root
    password: 123456Qazwsx.
    
  jpa: 
    hibernate:
      ddl-auto: none
      
      
logging:
  pattern:
    console: "%d - %msg%n"
    file: "%d - %msg%n"
  
  path: /home/ganger
  file: /home/ganger/paylog.txt
