server:
    port: 9081
    
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pay
    username: root
    password: 569767
    
  jpa: 
    hibernate:
      ddl-auto: none
